# ------------------------------------------------------------------------
# The test process is stopped,
# since I'll be no longer using/testing this project.
# ------------------------------------------------------------------------

# sudo: required
# services:
#   - docker

# before_install:
#   - docker build -t victortsokonov/docker-react -f Dockerfile.dev .

# script:
#   - docker run -e CI=true victortsokonov/docker-react npm run test

# ------------------------------------------------------------------------
# The deployment process is stopped,
# since I terminated my application in AWS.
# ------------------------------------------------------------------------

# deploy:
#   provider: elasticbeanstalk
#   region: "eu-central-1"
#   app: "docker-react"
#   env: "Docker-react-env-1"
#   bucket_name: elasticbeanstalk-eu-central-1-187969420637
#   bucket_path: "docker-react"
#   on:
#     branch: main
#   access_key_id: "$AWS_ACCESS_KEY"
#   secret_access_key: "$AWS_SECRET_ACCESS_KEY"

# ------------------------------------------------------------------------
