version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
# docker-compose -f docker-compose-dev.yml up
# docker-compose -f docker-compose-dev.yml up --build
# docker-compose -f docker-compose-dev.yml down
